# Generated by Django 4.2.7 on 2025-11-17 07:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_user_bio_user_position_user_supervisor_and_more'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='اسم النوع')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('color', models.CharField(default='#1976d2', max_length=7, verbose_name='اللون')),
                ('icon', models.CharField(blank=True, max_length=50, null=True, verbose_name='الأيقونة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'نوع المهمة',
                'verbose_name_plural': 'أنواع المهام',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='taskevaluation',
            options={'ordering': ['-evaluated_at'], 'verbose_name': 'تقييم المهمة', 'verbose_name_plural': 'تقييمات المهام'},
        ),
        migrations.AddField(
            model_name='task',
            name='actual_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='الساعات الفعلية'),
        ),
        migrations.AddField(
            model_name='task',
            name='estimated_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='الساعات المقدرة'),
        ),
        migrations.AddField(
            model_name='task',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ البدء'),
        ),
        migrations.AddField(
            model_name='task',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_tasks', to=settings.AUTH_USER_MODEL, verbose_name='المشرف'),
        ),
        migrations.AddField(
            model_name='task',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='accounts.team', verbose_name='الفريق'),
        ),
        migrations.AddField(
            model_name='taskevaluation',
            name='criteria',
            field=models.CharField(choices=[('quality', 'الجودة'), ('speed', 'السرعة'), ('communication', 'التواصل'), ('problem_solving', 'حل المشاكل'), ('teamwork', 'العمل الجماعي'), ('overall', 'التقييم العام')], default='overall', max_length=20, verbose_name='المعيار'),
        ),
        migrations.AddField(
            model_name='taskevaluation',
            name='evaluated_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_evaluations', to=settings.AUTH_USER_MODEL, verbose_name='الموظف المقيم'),
        ),
        migrations.AddField(
            model_name='taskevaluation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('pending', 'قيد الانتظار'), ('in_progress', 'قيد التنفيذ'), ('completed', 'مكتمل'), ('cancelled', 'ملغي'), ('on_hold', 'معلّق')], default='pending', max_length=20, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='taskevaluation',
            name='evaluated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_evaluations', to=settings.AUTH_USER_MODEL, verbose_name='قيم بواسطة'),
        ),
        migrations.AlterField(
            model_name='taskevaluation',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='tasks.task', verbose_name='المهمة'),
        ),
        migrations.CreateModel(
            name='TaskImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='task_images/', verbose_name='الصورة')),
                ('caption', models.CharField(blank=True, max_length=200, null=True, verbose_name='التعليق')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الرفع')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='tasks.task', verbose_name='المهمة')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='رفع بواسطة')),
            ],
            options={
                'verbose_name': 'صورة المهمة',
                'verbose_name_plural': 'صور المهام',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='المحتوى')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('edited', models.BooleanField(default=False, verbose_name='تم التعديل')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='tasks.taskcomment', verbose_name='الرد على')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tasks.task', verbose_name='المهمة')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_comments', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'تعليق المهمة',
                'verbose_name_plural': 'تعليقات المهام',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='task',
            name='task_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='tasks.tasktype', verbose_name='نوع المهمة'),
        ),
    ]
