# Generated by Django 4.2.7 on 2025-11-17 07:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0002_tasktype_alter_taskevaluation_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'تم الإنشاء'), ('updated', 'تم التحديث'), ('status_changed', 'تم تغيير الحالة'), ('assigned', 'تم التعيين'), ('unassigned', 'تم إلغاء التعيين'), ('completed', 'تم الإتمام'), ('reopened', 'تم إعادة الفتح'), ('deleted', 'تم الحذف')], max_length=20, verbose_name='الإجراء')),
                ('old_value', models.TextField(blank=True, null=True, verbose_name='القيمة القديمة')),
                ('new_value', models.TextField(blank=True, null=True, verbose_name='القيمة الجديدة')),
                ('field_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='اسم الحقل')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التغيير')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_history_actions', to=settings.AUTH_USER_MODEL, verbose_name='تم التغيير بواسطة')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='tasks.task', verbose_name='المهمة')),
            ],
            options={
                'verbose_name': 'سجل المهمة',
                'verbose_name_plural': 'سجلات المهام',
                'ordering': ['-created_at'],
            },
        ),
    ]
